apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-app-pvc
  namespace: wp
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi